-- 코드를 입력하세요
SELECT FO.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
# SELECT *
FROM FOOD_ORDER AS FO
JOIN FOOD_PRODUCT AS FP
ON FO.PRODUCT_ID = FP.PRODUCT_ID
WHERE DATE_FORMAT(FO.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY FO.PRODUCT_ID
# HAVING YEAR(IN_DATE) = '2022' AND MONTH(IN_DATE) = '05'
# HAVING DATE_FORMAT(FO.IN_DATE, '%Y-%m') = '2022-05'
ORDER BY SUM(FP.PRICE * FO.AMOUNT)  DESC, FO.PRODUCT_ID;

