# select FIRST_HALF.FLAVOR
SELECT FIRST_HALF.FLAVOR
from FIRST_HALF JOIN JULY
on FIRST_HALF.FLAVOR = JULY.FLAVOR
GROUP BY FLAVOR
ORDER BY SUM(FIRST_HALF.TOTAL_ORDER) + SUM(JULY.TOTAL_ORDER) DESC
LIMIT 3
